### ISSUE TITLE
Andorid project compile error, needing native_app_glue.

### ISSUE THREAD

**Issue by jayzhen521** [LukasBanana/LLGL#106]
I tried to run ./GenerateProjectAndroid.sh, an error occurred:
![image](https://github.com/LukasBanana/LLGL/assets/36140554/a0b95629-1d1d-4707-b25f-784a27d4d31b)
If I cut sinppet from example/CMakeLists.txt and paste to top CMakeLists.txt
![image](https://github.com/LukasBanana/LLGL/assets/36140554/ba5429af-8cc5-4126-971c-930b8045b10f)
to
![image](https://github.com/LukasBanana/LLGL/assets/36140554/34261c9e-c501-40be-a951-8d67f00775b7)
It works.

Is this an error needing to be fixed or a better way to modify?

**Comment by LukasBanana** [comment]
I should have removed that file long ago. I have a new file `BuildAndroid.bat` in my local repository, but I haven't spent any time on it in a while so the Android port never got out of an experimental state. The new batch script was supposed to follow a similar pattern as the other `Build*` scripts, but if you found a fix to make it work, please feel free to file a PR.

Are you working with Android Studio or what IDE do you generate the project files for with this script?

**Comment by jayzhen521** [comment]
Thank you for your reply!

> Are you working with Android Studio or what IDE do you generate the project files for with this script?

I'm using cygwin + androidndk(windows edition) + cmake(windows edition) to create LLGL and LLGL_OpenGL library.

My project mainly contains three layers:
1. rendering layer(bottom layer)
2. logic layer(middle layer)
3. business layer(top layer)

rendering layer can create render context and run rendering command( so business layer don't care about surface creation...)
logic layer contains data and operation
top layer written in java/kotlin for creating activity, etc.


I find some building error,:
1:
![image](https://github.com/LukasBanana/LLGL/assets/36140554/8c222988-7596-46f7-8788-6d529c5fd2b1)
It seems that the Surface::ProcessEvents method appears suddenly, and PostQuit(); does not belong to this class either.
![image](https://github.com/LukasBanana/LLGL/assets/36140554/546fc630-0d55-4cfe-a105-dc0beb94f622)

2:
![image](https://github.com/LukasBanana/LLGL/assets/36140554/86ccdb3d-3181-4a13-a03a-bcfc7389167c)
![image](https://github.com/LukasBanana/LLGL/assets/36140554/cee17237-1b32-4b26-90fa-15a849993ae1)

I'll list the problems I found here first and file a PR later.

**Comment by LukasBanana** [comment]
Thanks for the pointers. I can reproduce the issues with MSYS2 (based on Cygwin). I will try to find some time over the weekend to get the Android port back into a better state.

**Comment by LukasBanana** [comment]
I went ahead and fixed the issues with the commit above. Please open a new ticket for any runtime related issues.
