### ISSUE TITLE
[Dx11] SwapChain doesn't preserve debug name after resize

### ISSUE THREAD

**Issue by duckdoom4** [LukasBanana/LLGL#110]
Not sure how you want to implement this, so thought I'd make it an issue instead of a PR.

After `D3D11SwapChain::ResizeBackBuffer` destroys the old buffers and calls `CreateBackBuffer();` the second time, the new buffers don't get the debug name assigned if one was assigned during initialization.

So after the call it should call `SetDebugName(debugName);`. Could either store a copy of the name or maybe retrieve it from the private data before the destruction of the old buffers?

**Comment by LukasBanana** [comment]
Fixed with eb8a957.
