### ISSUE TITLE
Failed shader compile crashes

### ISSUE THREAD

**Issue by duckdoom4** [LukasBanana/LLGL#112]
After [the change](https://github.com/LukasBanana/LLGL/commit/839448277b40d97a63db7037b54b74c8c1e02bf2) that removed the native shader class, llgl now crashes if a shader fails to compile. (Eg. Syntax error in the hlsl)

Not sure if you want to support this, but it worked before the change so thought I'd let you know

**Comment by LukasBanana** [comment]
Added some more fixes and new unit test with f651f05 to prevent this from breaking in the future. Shader and PSO creation should fail gracefully without crashing.
