### ISSUE TITLE
Texture2DArray and Vulkan

### ISSUE THREAD

**Issue by st0rmbtw** [LukasBanana/LLGL#121]
I get this validation error on each draw call when using `Texture2DArray`'s with the `Vulkan` backend:
```
Validation Error: [ VUID-vkCmdDraw-viewType-07752 ] Object 0: handle = 0x2064730000068139, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0xc5801d0000000131, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x73ed4ff5 | vkCmdDraw():  the descriptor (VkDescriptorSet 0x2064730000068139[], binding 1, index 0) ImageView type is VK_IMAGE_VIEW_TYPE_2D_ARRAY but the OpTypeImage has (Dim = 2D) and (Arrayed = 0). The Vulkan spec states: If a VkImageView is accessed as a result of this command, then the image view's viewType must match the Dim operand of the OpTypeImage as described in Instruction/Sampler/Image View Validation (https://vulkan.lunarg.com/doc/view/1.3.283.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdDraw-viewType-07752)
```

No problems on other backends (`D3D11`, `OpenGL`) though.

Here's how I initialize the texture:
```cpp
LLGL::TextureDescriptor texture_desc;
texture_desc.type = LLGL::TextureType::Texture2DArray;
texture_desc.extent = LLGL::Extent3D(width, height, 1);
texture_desc.arrayLayers = layers;
texture_desc.bindFlags = LLGL::BindFlags::Sampled;
texture_desc.cpuAccessFlags = 0;
texture_desc.miscFlags = 0;

Renderer::Context()->CreateTexture(texture_desc);
```
Here's the pipeline layout descriptor:
```cpp
#if defined(BACKEND_OPENGL)
    constexpr uint32_t samplerBinding = 1;
#else
    constexpr uint32_t samplerBinding = 2;
#endif

LLGL::PipelineLayoutDescriptor pipelineLayoutDesc;
pipelineLayoutDesc.bindings = {
    LLGL::BindingDescriptor(
        "UniformBuffer",
        LLGL::ResourceType::Buffer,
        LLGL::BindFlags::ConstantBuffer,
        LLGL::StageFlags::GeometryStage,
        0
    ),
    LLGL::BindingDescriptor("u_texture_array", LLGL::ResourceType::Texture, LLGL::BindFlags::Sampled, LLGL::StageFlags::FragmentStage, 1),
    LLGL::BindingDescriptor("u_sampler", LLGL::ResourceType::Sampler, 0, LLGL::StageFlags::FragmentStage, samplerBinding),
};
```

Here's the fragment shader:
```glsl
#version 450 core

#extension GL_ARB_separate_shader_objects : enable

layout(set = 0, binding = 1) uniform texture2DArray u_texture_array;
layout(set = 0, binding = 2) uniform sampler u_sampler;

layout(location = 0) in vec2 g_uv;
layout(location = 1) flat in uint g_tile_id;

layout(location = 0) out vec4 color;


void main() {
    color = texture(sampler2DArray(u_texture_array, u_sampler), vec3(g_uv, float(g_tile_id)));
}
```

**Comment by LukasBanana** [comment]
I finally added Vulkan/GLSL and SPIR-V shaders to the PBR example (17800ec) because I noticed I never actually tested the _Texture2DArray_ type for the Vulkan backend. This example works fine, except for another validation error which seems negligible for now.

The only issue I see with your texture descriptor is that your `bindFlags` are only `Sampled`, which is fine as long as you never generate MIP-maps on that texture - writing them via `WriteTexture` would be ok, but automatic MIP generation requires render targets internally. In that case, you'll also have to add `ColorAttachment` (see [`GenerateMips`](https://github.com/LukasBanana/LLGL/blob/master/include/LLGL/CommandBuffer.h#L327) docs).

Looking at your validation error, it seems the problem is the SPIR-V module, not the Vulkan API use because it states _"ImageView type is VK_IMAGE_VIEW_TYPE_2D_ARRAY"_, which is what you want from LLGL, but later it states _"OpTypeImage has (Dim = 2D) and (Arrayed = 0)"_ indicating that the SPIR-V module expects a non-arrayed 2D texture. Have you looked at a RenderDoc capture to make sure your SPIR-V shader expects the resource types you intended?

**Comment by st0rmbtw** [comment]
I'm not really sure, but looks like it's fine. SPIR-V expects texture2DArray as it should.
![image](https://github.com/user-attachments/assets/78981b37-9904-4891-98c0-387e793378da)

**Comment by st0rmbtw** [comment]
And also in SPIR-V inspector the arrayed flag is 1, but the error says that it is 0'.
![image](https://github.com/user-attachments/assets/5c6f6196-ea1f-459a-9c01-1e5542067a05)

**Comment by LukasBanana** [comment]
Does it render the wrong result or is it only the validation error showing up? In that case might be worth updating the Vulkan SDK. I will say, though, that LLGL does modify the SPIR-V module when working with uniforms (i.e. [`PipelineLayoutDescriptor::uniforms`](https://github.com/LukasBanana/LLGL/blob/master/include/LLGL/PipelineLayoutFlags.h#L420)), but in your case, that shouldn't be happening.

**Comment by st0rmbtw** [comment]
The result of render is perfectly fine, only validation error.

**Comment by LukasBanana** [comment]
When I put your shader into [shader-playground](https://shader-playground.timjones.io/5101f60a5c972ca3ae8e1f838d8f9105) and compare the `OpTypeImage` with the [SPIR-V specification](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpTypeImage) everything looks correct:
```
OpTypeImage %float 2D 0 1 0 1 Unknown
                    ^ ^ ^ ^ ^    ^
                    | | | | |    `- Image format
                    | | | | `------ Sampled
                    | | | `-------- MS
                    | | `---------- Arrayed
                    | `------------ Depth
                    `-------------- Dim
```
This contradicts the validation error. 

It looks like others had similar experiences with the validation layer, but this ticket was closed without any changes to the implementation: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4321
I would first update the Vulkan SDK or respond in that ticket as this looks like a false positive to me.

**Comment by st0rmbtw** [comment]
Updated Vulkan SDK and GPU driver, and it became even worse.
New validation error is showing up:
```
Validation Error: [ VUID-vkCmdBeginRenderPass-contents-09640 ] Object 0: handle = 0x2d1bcbc7f00, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x40fb83eb | vkCmdBeginRenderPass(): contents is VK_SUBPASS_CONTENTS_INLINE_AND_SECONDARY_COMMAND_BUFFERS_KHR, but nestedCommandBuffer nor maintenance7 were not enabled. The Vulkan spec states: If contents is VK_SUBPASS_CONTENTS_INLINE_AND_SECONDARY_COMMAND_BUFFERS_KHR, then at least one of the following features must be enabled: maintenance7 nestedCommandBuffer (https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdBeginRenderPass-contents-09640)
```

**Comment by LukasBanana** [comment]
This is the same validation error I just saw when testing the PBR example with Vulkan. 68f7b57 should fix that. Feel free to re-open the ticket if the issue persists.

**Comment by st0rmbtw** [comment]
@LukasBanana
I think I found the problem.
New Vulkan version gives more information about that error.

Now it looks like this:
```
Validation Error: [ VUID-vkCmdDraw-viewType-07752 ] Object 0: handle = 0x4d33f3000004bc1c, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0xa9fdf000000014c, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x73ed4ff5 | vkCmdDraw():  the descriptor VkDescriptorSet 0x4d33f3000004bc1c[] [Set 0, Binding 1, Index 0, variable "u_texture"] ImageView type is VK_IMAGE_VIEW_TYPE_2D_ARRAY but the OpTypeImage has (Dim = 2D) and (Arrayed = 0). The Vulkan spec states: If a VkImageView is accessed as a result of this command, then the image view's viewType must match the Dim operand of the OpTypeImage as described in Instruction/Sampler/Image View Validation (https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdDraw-viewType-07752)
```
And I noticed it complains about the 'u_texture' uniform from another shader that is texture2D.

My render system looks like this:
`Begin();`
`RenderWorld();`
`RenderSpriteBatch();`
`End();`

where 
`Begin()` is:
```cpp
commands->Begin();
commands->BeginRenderPass(*swap_chain);
commands->Clear(LLGL::ClearFlags::Color, LLGL::ClearValue(0.0f, 0.0f, 0.0f, 1.0f));
commands->SetViewport(swap_chain->GetResolution());
```
`RenderWorld()` is:
```cpp
for (const auto& entry : world.render_chunks()) {
    const RenderChunk& chunk = entry.second;

    if (chunk.blocks_empty()) continue;

    TilemapUniforms uniforms = TilemapUniforms {
        .projection = m_projection_matrix,
        .view = m_view_matrix,
        .transform = chunk.transform_matrix,
    };
    commands->UpdateBuffer(*m_constant_buffer, 0, &uniforms, sizeof(uniforms));

    const Texture& t = Assets::GetTexture(AssetKey::TextureTiles);

    commands->SetPipelineState(*m_world_pipeline);
    commands->SetVertexBuffer(*chunk.block_vertex_buffer);
    commands->SetResource(0, *m_constant_buffer);
    commands->SetResource(1, *t.texture);
    commands->SetResource(2, Assets::GetSampler(t.sampler));

    commands->Draw(chunk.blocks_count, 0);
}
```
`RenderSpriteBatch()` is:
```cpp
commands->SetVertexBuffer(*m_vertex_buffer);
commands->SetIndexBuffer(*m_index_buffer);

commands->SetPipelineState(*m_sprite_pipeline);
commands->SetResource(0, *m_constant_buffer);
commands->SetResource(1, *t.texture);
commands->SetResource(2, Assets::GetSampler(t.sampler));
commands->DrawIndexed(m_index_count, 0, vertex_offset);
```
`End()` is:
```cpp
commands->EndRenderPass();
commands->End();

queue->Submit(*commands);

swap_chain->Present();
```

Sprite batch pipeline layout:
```cpp
#ifdef BACKEND_OPENGL
    constexpr uint32_t samplerBinding = 1;
#else
    constexpr uint32_t samplerBinding = 2;
#endif

LLGL::PipelineLayoutDescriptor pipelineLayoutDesc;
pipelineLayoutDesc.bindings = {
    LLGL::BindingDescriptor(
        "UniformBuffer",
        LLGL::ResourceType::Buffer,
        LLGL::BindFlags::ConstantBuffer,
        LLGL::StageFlags::VertexStage,
        0
    ),
    LLGL::BindingDescriptor("u_texture", LLGL::ResourceType::Texture, LLGL::BindFlags::Sampled, LLGL::StageFlags::FragmentStage, 1),
    LLGL::BindingDescriptor("u_sampler", LLGL::ResourceType::Sampler, 0, LLGL::StageFlags::FragmentStage, samplerBinding),
};

LLGL::PipelineLayout* pipelineLayout = state.context->CreatePipelineLayout(pipelineLayoutDesc);
```

World pipeline layout:
```cpp
#if defined(BACKEND_OPENGL)
    constexpr uint32_t samplerBinding = 1;
#else
    constexpr uint32_t samplerBinding = 2;
#endif

LLGL::PipelineLayoutDescriptor pipelineLayoutDesc;
pipelineLayoutDesc.bindings = {
    LLGL::BindingDescriptor(
        "UniformBuffer",
        LLGL::ResourceType::Buffer,
        LLGL::BindFlags::ConstantBuffer,
        LLGL::StageFlags::GeometryStage,
        0
    ),
    LLGL::BindingDescriptor("u_texture_array", LLGL::ResourceType::Texture, LLGL::BindFlags::Sampled, LLGL::StageFlags::FragmentStage, 1),
    LLGL::BindingDescriptor("u_sampler", LLGL::ResourceType::Sampler, 0, LLGL::StageFlags::FragmentStage, samplerBinding),
};
```

So I think the pipeline sometimes is not changed and for example the draw command in `RenderWorld()` uses the pipeline from `RenderSpriteBatch()`

**Comment by st0rmbtw** [comment]
I just changed the indexes of bindings and the validation error is gone.

**Comment by LukasBanana** [comment]
> So I think the pipeline sometimes is not changed

Can you confirm this in a RenderDoc capture by also adding debug names to both PSOs? You can use `debugName` from the descriptor structure or `SetDebugName()` function on the `PipelineState` objects.

**Comment by st0rmbtw** [comment]
@LukasBanana I think I was wrong about not changed pipeline because if it really used the wrong pipeline, then the program would crash because the shaders and other pipeline settings would be wrong

**Comment by LukasBanana** [comment]
Have you tried the fix I submitted? I see your fork is a bit out of date, maybe you can try against the latest revision.

**Comment by st0rmbtw** [comment]
> Have you tried the fix I submitted? I see your fork is a bit out of date, maybe you can try against the latest revision.

Yes, https://github.com/LukasBanana/LLGL/commit/68f7b57709d64176678f420f0e0fb1ea361657f9 fixed this validation error: https://github.com/LukasBanana/LLGL/issues/121#issuecomment-2254595750

But it didn't fix the error described in the issue, but there is a workaround: use different bindings in each shader.
That's weird anyway, it's understandable if bindings overlap in the same pipeline, but there are two different pipelines.
