### ISSUE TITLE
Static samplers don't work in Vulkan.

### ISSUE THREAD

**Issue by st0rmbtw** [LukasBanana/LLGL#141]
When I use `LLGL::PipelineLayoutDescriptor::staticSamplers` I get this validation error:
```
Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-layout-07988 ] Object 0: handle = 0xbb99190000000253, type = VK_OBJECT_TYPE_SHADER_MODULE; Object 1: handle = 0x5caeea00000002df, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; | MessageID = 0x215f02cd | vkCreateGraphicsPipelines(): pCreateInfos[0].pStages[1] SPIR-V (VK_SHADER_STAGE_FRAGMENT_BIT) uses descriptor [Set 0, Binding 4, variable "u_background_sampler"] (type VK_DESCRIPTOR_TYPE_SAMPLER or VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER) but was not declared in the pipeline layout. The Vulkan spec states: If a resource variables is declared in a shader, a descriptor slot in layout must match the shader stage (https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/1.3-extensions/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-layout-07988)
```

**UPD**:

Also, it says that it doesn't see the texture binding in the pipeline layout, even though it's there.
Here's the validation error:
```
Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-layout-07988 ] Object 0: handle = 0x3ed3570000000255, type = VK_OBJECT_TYPE_SHADER_MODULE; Object 1: handle = 0x9f30780000000358, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; | MessageID = 0x215f02cd | vkCreateGraphicsPipelines(): pCreateInfos[0].pStages[1] SPIR-V (VK_SHADER_STAGE_FRAGMENT_BIT) uses descriptor [Set 0, Binding 4, variable "u_texture_array"] (type VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER or VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE) but was not declared in the pipeline layout. The Vulkan spec states: If a resource variables is declared in a shader, a descriptor slot in layout must match the shader stage (https://vulkan.lunarg.com/doc/view/1.3.290.0/windows/1.3-extensions/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-layout-07988)
```
Looks like bindings in Vulkan are broken (But only for textures and samplers).

**Comment by LukasBanana** [comment]
It's interesting that the validation layer mentions this one sampler but not the other two that you have in that shader ([postprocess.frag:6](https://github.com/st0rmbtw/TerrariaCloneCpp/blob/main/assets/shaders/vulkan/postprocess.frag#L6)).
I just fixed the binding points in the _ResourceBinding_ example (d829d8a), which makes use of static samplers. Does that example work for you with Vulkan?

**Comment by st0rmbtw** [comment]
> It's interesting that the validation layer mentions this one sampler but not the other two that you have in that shader

It actually mentions all of them :). Sorry, I should have said that in the description.

> I just fixed the binding points in the _ResourceBinding_ example ([d829d8a](https://github.com/LukasBanana/LLGL/commit/d829d8a9e9ab414e3057139d5962f884cde40497)), which makes use of static samplers. Does that example work for you with Vulkan?

Let me check

**Comment by st0rmbtw** [comment]
`ResourceBinding` example crashes with this error:
```
in 'LLGL::BuildPushConstantRanges': assertion failed: 'uniformRanges[i].size() == outUniformRanges.size()'
```

**Comment by LukasBanana** [comment]
That looks like you aren't building with `LLGL_ENABLE_SPIRV_REFLECT`, perhaps some CMake cache issue? What does the debugger say about these arrays?

**Comment by st0rmbtw** [comment]
> That looks as if you aren't building with `LLGL_ENABLE_SPIRV_REFLECT`, perhaps some CMake cache issue?

Yep, that was a CMake cache issue. The example works fine. There are some problems in my code then.

**Comment by st0rmbtw** [comment]
I still haven't found the issue. I've checked everything.

When I moved samplers from `staticSamplers` into `bindings` it solved the issue for this pipeline https://github.com/st0rmbtw/TerrariaCloneCpp/blob/5c034c4e72ad81bb9fbc45a4020817f099e45b8e/src/renderer/renderer.cpp#L211C5-L250C77

But it didn't solve for this one: https://github.com/st0rmbtw/TerrariaCloneCpp/blob/5c034c4e72ad81bb9fbc45a4020817f099e45b8e/src/renderer/world_renderer.cpp#L33C5-L94C61
And for this one:
https://github.com/st0rmbtw/TerrariaCloneCpp/blob/5c034c4e72ad81bb9fbc45a4020817f099e45b8e/src/renderer/particle_renderer.cpp#L99C5-L159C61

And also, it doesn't see the texture in bindings in the pipeline of the world renderer.

I have a wild guess that in `Vulkan` when `heapBindings` is used it breaks something.

**Comment by LukasBanana** [comment]
I synced your project against [f38292c](https://github.com/st0rmbtw/TerrariaCloneCpp/commit/f38292c85dade6cc39eed7e77ec0c8b36a1d8fc1) and after enabling `LLGL_ENABLE_SPIRV_REFLECT` everything seems to look normal (I do see validation errors, but they seem to be unrelated to static sampler or heap bindings):
![TerrariaCloneCpp_1-Vk](https://github.com/user-attachments/assets/57441815-76a6-4fa7-b70b-9c6ac857fe71)

Am I missing something? That branch does include static samplers and resource heaps. I compiled the SPIR-V shaders with glslangValidator manually. I also had some build issues with your included freetype version using Visual Studio 2022 Community Edition, so I had to redirect it to my own build.

**Comment by st0rmbtw** [comment]
Ah, yeah, it was the `LLGL_ENABLE_SPIRV_REFLECT` issue. Sorry, I didn't know it was necessary to enable it.

**Comment by LukasBanana** [comment]
No worries, we are figuring things out as we're using these features more often. I will add some more assertions and documentation to make it clear when this CMake option is necessary as this is not obvious. The rationale behind it was to allow LLGL to be built without any thirdparty dependencies, but SPIRV-Headers is hard to avoid when shader reflection is needed.

You can update resource heaps with [`RenderSystem::WriteResourceHeap()`](https://github.com/LukasBanana/LLGL/blob/master/include/LLGL/RenderSystem.h#L487).
