### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [LukasBanana/LLGL#2]
I would like to point out that an identifier like "[`__LLGL_COMMAND_BUFFER_H__`](https://github.com/LukasBanana/LLGL/blob/837bfa6568b05caff14a3a5685956ed341e61c78/include/LLGL/CommandBuffer.h#L8)" [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by LukasBanana** [comment]
Thank's for the hint, I always used this identifier syntax in my projects and with the repsective Project name prefix (here "LLGL_") I never had a problem with that.
But I will fix this as soon as possible.

**Comment by oleid** [comment]
How about  using a "#pragma once" instead of a preprocessor guard?

**Comment by LukasBanana** [comment]
I know "#pragma once" is implemented in most C++ compilers, but since it's not part of the C++ standard, I'd like to use header guards instead.

**Comment by LukasBanana** [comment]
Renamed all header guards from "__LLGL_..._H__" to "LLGL_..._H".

**Comment by elfring** [comment]
Thanks for [your improvement of affected identifiers](https://github.com/LukasBanana/LLGL/commit/e6aba26824ecce34f7197795d891e7bc3e244821 "Deletion of several underscores").
