### ISSUE TITLE
OpenGL ES support

### ISSUE THREAD

**Issue by sazlang** [LukasBanana/LLGL#23]

**Comment by LukasBanana** [comment]
Could you please add a full question.

**Comment by sazlang** [comment]
Are you planning to add OpenGL ES support in the future?

**Comment by LukasBanana** [comment]
I moved some of the OpenGL code into the GLCommon/ directory in case I want to add an OpenGL ES backend sometime.
However, I haven't made concrete plans how and when I'll add such a backend.
**Vulkan** and **Metal** are the major candidates for mobile platforms.
