### ISSUE TITLE
Remove an unnecessary check for an API handle

### ISSUE THREAD

**Issue by elfring** [LukasBanana/LLGL#24]
[An extra check is not needed for a zero API handle](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDeleteSync.xhtml "Description from the OpenGL reference") in [the function “`GLFence::Release`](https://github.com/LukasBanana/LLGL/blob/55d753bd851a16fa09cc0a55647f458ce760636f/sources/Renderer/OpenGL/RenderState/GLFence.cpp#L50 "Update candidate")”.

**Comment by LukasBanana** [comment]
Thanks for the hint, I didn't noticed it yet.
However, I think the benefit is rather low since the the condition spares the first unnecessary call to `glDeleteSync`.
I don't know the exact overhead of a GL command like this, but I think this simple condition is worth it.

**Comment by elfring** [comment]
I suggest still to avoid the mentioned redundant condition check.
Will a bit less code trigger desirable effects?

**Comment by LukasBanana** [comment]
What do you mean by desirable effects?
How much is this simple condition an issue in your point of view?

**Comment by elfring** [comment]
It is just one source code place where a simple adjustment can make sense.

**Comment by LukasBanana** [comment]
When you use a debugging tool like RenderDoc and you see that LLGL first calls `glDeleteSync` before it called `glFenceSync` for the first time, that does not look very sensible to me.

**Comment by elfring** [comment]
Function call sequences (which might look strange) can occasionally happen while they should still work according to the documented programming interfaces.

**Comment by LukasBanana** [comment]
So you're suggestion the following solution?
```cpp
GLFence::~GLFence()
{
    glDeleteSync(sync_);
}

void GLFence::Submit()
{
    if (HasExtension(GLExt::ARB_sync))
    {
        glDeleteSync(sync_);
        sync_ = glFenceSync(GL_SYNC_GPU_COMMANDS_COMPLETE, 0);
    }
}
```
Before I change it, I have two more question:
1. Why haven't you just created a pull request for this small solution?
2. Are you using LLGL anyway?

**Comment by elfring** [comment]
1. I found it easier to clarify a possible small change in the implementation of the member function “`GLFence::Release`” in this way.
2. I try to improve software also another bit before I am going to use it in more detail.

**Comment by LukasBanana** [comment]
Done with [d2b9e07](https://github.com/LukasBanana/LLGL/commit/d2b9e07b7f3607c4d90ccef2c8fb1445e468c8ba).

**Comment by elfring** [comment]
Thanks for [your small source code adjustment](https://github.com/LukasBanana/LLGL/commit/d2b9e07b7f3607c4d90ccef2c8fb1445e468c8ba "Simplified implementation of GLFence.").

**Comment by LukasBanana** [comment]
You wrote the message "Thanks for your small source code adjustment" 3 times in the exact same way.
My condolences, you failed the Turing test.
