### ISSUE TITLE
Internal memory allocation callbacks

### ISSUE THREAD

**Issue by raxvan** [LukasBanana/LLGL#25]
Does LLGL have support for host memory allocations callbacks ? Such as VkAllocationCallbacks for vulkan? How about other apis (dx, ogl, etc) and other library allocations ?

If not, is this planned ?

**Comment by LukasBanana** [comment]
The Vulkan backend is still in an experimental state. Compared to the D3D12 and Metal backends more usable, though.
However, right now there is no such interface to control the Vulkan allocation model.
I currently also have no plans when and how I implement this.
As long as the Vulkan backend does not have significiantly better performance than the D3D11 and GL backends, I don't see the necessity for such fine grained memory control.

**Comment by ForgeMistress** [comment]
What about memory control of the internal structures that LLGL itself allocates? Is there a way for us to define allocation routines for the library as a whole?

**Comment by ForgeMistress** [comment]
I guess an alternative then is to overload the default new and delete. I've got allocation tracking for leak detection and a few cache coherence tricks I'm using to squeeze some perf out of my framework.

**Comment by LukasBanana** [comment]
This ticket got stale. There feature doesn't have priority so I will close this as _Won't Fix_.
