### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [LukasBanana/LLGL#3]
Would you like to [replace any double quotes](https://github.com/LukasBanana/LLGL/blob/5fa82c7d4f018376393df12ceeaa8cb92cfbc165/include/LLGL/LLGL.h#L12 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by LukasBanana** [comment]
Could you please explain why this is meaningful? I typically distinguish between these two forms of include directives on purpose, to avoid mismatches with header files from the preprocessor environment.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by LukasBanana** [comment]
From the last link you posted:

> #include "file"
>     This variant is used for header files **of your own program**.

And that's what I want for those files, because they are not system files, as it is mentioned from the link for angle brackets:

> #include <file>
>     This variant is used for system header files.

So I currently don't see why it should be replaced.

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
* Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
* Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?

**Comment by LukasBanana** [comment]
For the time being I'll keep it as it is.

**Comment by elfring** [comment]
I suggest to distinguish better between the include style for ordinary programs and customised libraries.
How much do you care where the include files are safely stored for a software library?
