### ISSUE TITLE
compile OpenGLES for IOS using CMake

### ISSUE THREAD

**Issue by CaichaoGitHub** [LukasBanana/LLGL#34]
i was implementing a es version in IOS project, i met a compile problem ;
build pipeline1
cmake -> ios xcproject -> using xcode build -> succeed 

build pipeline2
cmake -> default project -> using cmake build -> failed 

while building LLGL ,it succeed , and building LLGL_ES3 , it failed,

my error:
![屏幕快照 2019-03-11 11 37 31](https://user-images.githubusercontent.com/12059897/54099039-4927c300-43f2-11e9-8bb7-f612e155e0a1.png)

**Comment by CaichaoGitHub** [comment]
#   define LLGL_EXPORT __attribute__((visibility("default"))) fix the problem

**Comment by LukasBanana** [comment]
I wasn't quick enough, but it seems you already found a solution.
I never really came to start with the GLES port, but would be great to hear more from your experience with porting LLGL to GLES :)

**Comment by CaichaoGitHub** [comment]
> I wasn't quick enough, but it seems you already found a solution.
> I never really came to start with the GLES port, but would be great to hear more from your experience with porting LLGL to GLES :)
> 
> I once thought about merging `GLCommon/`, `OpenGL/`, and `OpenGLES3/` folders and only use macros to separate GL and GLES code, since a lot of code could be shared between them.
> What is your approach?

i began developing es two days ago ;i was about to reuse your glcommon , and part of your codes in OPENGL , but i had no time to realize full features in LLGL,  depending on my projects.
Apple has deprecated OpenGL in ios12 , and google has supported vulkan in android7.0, so es would be weed out gradually, i thought make full support for metal/vulkan is a best choices
