### ISSUE TITLE
Would you give me some suggestion about how the command buffers work or any link would be helpful. ?

### ISSUE THREAD

**Issue by vedon** [LukasBanana/LLGL#35]

**Comment by LukasBanana** [comment]
The `CommandBuffer` interface mimics the API of D3D12, Vulkan, and Metal. For these APIs, the interface merely forwards the calls to underlying API (for the most part). For D3D11 and OpenGL, the implementation emulates the features of a command buffer. The default command buffer is very similar to the "Immediate Context" in D3D11, where the calls are submitted to the driver immediately. A "deferred" or "secondary" command buffer must guarantee to store commands in a buffer before they are submitted to the GPU. D3D12, Vulkan, and Metal support this feature natively, but for D3D11 and OpenGL it must be emulated, i.e. the actual API calls are executed when [`CommandQueue::Submit`](https://github.com/LukasBanana/LLGL/blob/master/include/LLGL/CommandQueue.h#L49) is called.

**Comment by vedon** [comment]
thx ,that helps me a lot .LOL.
