### ISSUE TITLE
SDL, X11 and GLFW backends?

### ISSUE THREAD

**Issue by ghost** [LukasBanana/LLGL#4]
Hello. Will support for SDL, X11 (Linux/Unix), and GLFW backends window support? Also, will support of Vulkan API? I very wait for Vulkan API support, as DirectX 12 too.

**Comment by LukasBanana** [comment]
I am currently quite busy with my master thesis, so I don't have much time to continue the D3D12 backend as well as the Vulkan backend which is only at its very beginning.

Regarding your interest of GLFW: Have you read chapter 6 "Custom Surtface Class" of the [Getting Started with LLGL](https://github.com/LukasBanana/LLGL/blob/master/docu/GettingStarted/Getting%20Started%20with%20LLGL.pdf) document?
It describes how to write a custom surface class with GLFW as example.
I never used SDL, but I think it should be possible to integrate it similarly like GLFW.
