### ISSUE TITLE
Create todo list

### ISSUE THREAD

**Issue by elgunhuseynli** [LukasBanana/LLGL#42]
Hi.
Thanks for for sharing this beautiful library with us. I would be glad to help this project with contributions. But I don't know which parts aren't implemented or need maintenance.

In readme file, project progress described with percentage. For example ~30% of Vulkan renderer is complete. Unfortunately percentage is not enough for new contributors. Isn't it better to create todo list of which parts are not done?

Good news is that github already has that feature in Projects tab.

**Comment by LukasBanana** [comment]
Good point, let me create a ticket with some major bullet points for that.
Which backends are you most interested/experienced in?

**Comment by LukasBanana** [comment]
Done with https://github.com/LukasBanana/LLGL/issues/43
