### ISSUE TITLE
Community discussion

### ISSUE THREAD

**Issue by julianxhokaxhiu** [LukasBanana/LLGL#53]
One thing I've found extremely useful while working with various Open Source projects is the ability to have a community to talk to, including the very same authors.

LLGL at the current state does not offer any kind of Discussion channel around this project. My proposal would be to either consider one of these following options:
- IRC
- Gitter
- Discord

---

# IRC
Although it's very used and popular, most of the people today are no more keen to download, install or use IRC in general. I would personally **NOT** suggest this option.

# Gitter
Although this platform is very popular among Developers, it's not really the best platform to chat into. Lack of rooms, is definitely a CONs. One of the biggest PROs is definitely the fact that to start chatting most probably the users already do have one of the required accounts to login.

# Discord
Pretty much used by gamers, but not only to. For eg. Microsoft is one of those having a Discord channel supporting also Developers. The fact you can create rooms and have also vocal rooms makes this definitely a very good platform to get in touch, also with non-written communication.

---

I would like to use this issue to solve and ideally choose the right platform in order to get in touch. I already have some questions regarding LLGL and Shader loading, but I fear I would fill the issue list a lot, and maybe not all the users may find it useful. As well as you being distracted by "managing issues" than actually focusing on the real problems.

Thank you in advance if you ever consider this!

**Comment by LukasBanana** [comment]
Thank you for bringing this up and laying out the pros and cons. I really like the idea of a community around this project, but since there haven't been many contributors yet I haven't taken much thought about it so far. But perhaps a community can grow with a proper communication channel.

Being able to use Gitter with your GitHub account is something I'd really appreciate.

That said, I don't have experience with either Gitter or Discord, I only heard about these services.

**Comment by LukasBanana** [comment]
I started with a [channel in Gitter](https://gitter.im/LLGL-Project/community#) for simplicity reasons. As soon as there is actually a community growing around this project, we can still discuss moving it on to Discord.

**Comment by xzores** [comment]
I am up for Discord
