### ISSUE TITLE
Is C# wrapper cross-platform?

### ISSUE THREAD

**Issue by elgunhuseynli** [LukasBanana/LLGL#55]
It seems like current C# wrapper using C++/CLI. (Correct me if I'm wrong)
Isn't C++/CLI only supported on Windows platform for now? Microsoft introduced C++/CLI support to .NET Core 3 but unfortunately it is only working on Windows.

PInvoke is the only option right now for cross-platform C# binding.

**Comment by LukasBanana** [comment]
Hi, I'm afraid you're right. I barely used C# on other platform other than Windows except a few times with Mono but no C/C++ bindings.
If you can refer me to some good references for portable C++ to C# bindings, let me know.

**Comment by mediabuff** [comment]
https://github.com/microsoft/CsWinRT

**Comment by jayrulez** [comment]
With the new C API, it will be easy to use this from C# now :)

**Comment by LukasBanana** [comment]
@jayrulez wouldn't that still require to also declare all enums and structs in C#, though?

**Comment by jayrulez** [comment]
Yes, that's still necessary but this is what everyone does anyway. Take a look at the bgfx bindings as an example: https://github.com/bkaradzic/bgfx/blob/master/bindings/cs/bgfx.cs

**Comment by LukasBanana** [comment]
Better late than never, but this is resolved with 8e00be1. It also includes two C# examples that are no longer using C++/CLI.
