### ISSUE TITLE
ShaderUniform for DX11 ?

### ISSUE THREAD

**Issue by BobbyBao** [LukasBanana/LLGL#6]
How to implement a extendible material system on dx11, use ConstBuffer?

**Comment by LukasBanana** [comment]
Hi, could you please describe your question in more detail?

How *extensible* should your material system be?
This sounds like a question about the typical issue of so called "Uber-Shaders" where you have all material effects inside a single (and commonly large) shader.

Or is this a question specifically about LLGL?

**Comment by BobbyBao** [comment]
A Material class, like Urho3D engine and Unity Engine, material contains a vector of ShaderParaments,  each shader parament set value by name，LLGL dx11 renderer should implement ShaderUniform interface or provide a reflection API

**Comment by LukasBanana** [comment]
The `ShaderUniform` interface is only for the older shader versions of GLSL to set individual uniforms.
In modern shaders you typically use *Uniform Buffers* (OpenGL) or *Constant Buffers* (Direct3D).

Take a look at the `constantBuffer` field in [Tutorial02](https://github.com/LukasBanana/LLGL/blob/master/tutorial/Tutorial02_Tessellation/main.cpp#L29).

**Comment by BobbyBao** [comment]
I kown, but ConstantBuffer shoulder privider reflection API. In a extensible material system, when you add a new shader, you only need to change a material config, instead of change the ConstBuffer struct in cpp source  code.

**Comment by LukasBanana** [comment]
The only shader reflection for constant buffers LLGL supports right now are the [`ShaderProgram::QueryConstantBuffers`](https://github.com/LukasBanana/LLGL/blob/master/include/LLGL/ShaderProgram.h#L78) function and [`ConstantBufferViewDescriptor`](https://github.com/LukasBanana/LLGL/blob/master/include/LLGL/BufferFlags.h#L168) structure.
But individual members of a constant buffer can not be queried.
So you need to know your shader structures and map them 1:1 into C++.

Even if I add this functionality at some day, I would not use the `ShaderUniform` interface, but I would extend the `ConstantBufferViewDescriptor` structure to support it.

However, I currently don't know when I have the time for this.

**Comment by LukasBanana** [comment]
This thread is quite old now, but might be related [this new ticket](https://github.com/LukasBanana/LLGL/issues/38).
