### ISSUE TITLE
vcpkg: LLGL installs header files in the wrong directory

### ISSUE THREAD

**Issue by mediabuff** [LukasBanana/LLGL#66]
https://github.com/microsoft/vcpkg/issues/15216#issue-771403297

Also, in windows I get, how do you build "LLGL_Direct3D11D.dll

**Comment by LukasBanana** [comment]
What do you mean? This is simply the debug build. All debug builds in LLGL get the "D" suffix. Just change your build configuration in Visual Studio to "Debug" and the CMake script should set the filename to `LLGL_Direct3D11D.dll`.

The include directory for LLGL should be set to `<PathToLLGL>/include`. For instance: `C:\Users\JohnDoe\MyCloneOfLLGL\include`. To include the library in your project you use the path `#include <LLGL/LLGL.h>`

**Comment by mediabuff** [comment]
I am using vcpkg. Vcpk installs under ../include/include/LLGL

please notice double ‘include’

also the Directx module is not built. Only the core dll is being built

**Comment by LukasBanana** [comment]
Closing this as it was fixed in a different repository with https://github.com/microsoft/vcpkg/pull/15366
