### ISSUE TITLE
WebGPU support?

### ISSUE THREAD

**Issue by unit-a-user** [LukasBanana/LLGL#67]
I would like to offer WebGPU support for LLGL. And almost directly, straight. Every function would be remap. And it was compiled into two files: JS (WebGPU access) and WebAssembly (residual C++).

**Comment by LukasBanana** [comment]
If you have a port ready just file a pull request. I'm not familiar with WebGPU myself and it seems this is still a work-in-progress API.

**Comment by LukasBanana** [comment]
Closing this as stale ticket. Feel free to open a PR if you want to provide a WebGPU port.
