### ISSUE TITLE
A suggestion, or bug...

### ISSUE THREAD

**Issue by Ivan-Sandro** [LukasBanana/LLGL#68]
When I run the program "RunExamplesWin64" and choose which example I want to run, the program returns saying that it did not find the specified path, I did not find the code for this program and I am a little lost, so maybe it is a bug, or I forgot something, if it's not a bug, and I forgot some step I should have taken to make this program work, why don't you create an executable that doesn't need installation and show all the features of your project in a simple way, so that anyone in a simple way can you see what your project can do, something already compiled?

I'm new in GitHub, I'm still getting the hang of things and my English is not so good ..., so I'm sorry for anything already.

**Comment by LukasBanana** [comment]
Did you download a [release build](https://github.com/LukasBanana/LLGL/releases) or the packaged repository?
The release builds contain pre-compiled binaries and should provide exactly what you are looking for.
If you download the repository as zip-archive you only get the source (and some content for the examples) but no binaries as you are supposed to build them yourself. That being said, as long as you have the prerequisites installed (such as VisualC++ and CMake), you can use the [BuildWin64.bat](https://github.com/LukasBanana/LLGL/blob/master/BuildWin64.bat) script to build from source and then run the RunExamplesWin64.bat script.

**Comment by Ivan-Sandro** [comment]
Oh, ok, I found the corrects files, thanks and sorry for the confusion.
