### ISSUE TITLE
build fails on arch-based distro

### ISSUE THREAD

**Issue by Ryder17z** [LukasBanana/LLGL#69]
Manjaro 21, using: https://aur.archlinux.org/packages/llgl-git/

Pamac output: [llgl-build.log](https://github.com/LukasBanana/LLGL/files/6799622/llgl-build.log)

**Comment by LukasBanana** [comment]
Fixed with [3b202cb](https://github.com/LukasBanana/LLGL/commit/3b202cbc5d5ba869d1faf22bed899dc848f624bd).

**Comment by LukasBanana** [comment]
Fixed wrong include header with [237521b](https://github.com/LukasBanana/LLGL/commit/237521b65d79065a4b34ef97581241d8c461aa24).
