### ISSUE TITLE
Mac OpenGL requires fragment shader

### ISSUE THREAD

**Issue by beldenfox** [LukasBanana/LLGL#71]
The Mac implementation of OpenGL requires a fragment shader even when rendering is only updating depth/shadow or stencil information. This is a violation of the OpenGL spec, the fragment shader should be optional in these cases. This affects the Shadow Mapping, Volume Rendering, and Stencil Buffer examples.

The work-around is to provide a fragment shader that consists of just a `main()` function that does nothing.

I don't know if LLGL should just document this quirk or provide a fragment shader internally to provide a consistent API across platforms.

**Comment by LukasBanana** [comment]
If this is a bug in macOS, LLGL should probably just provide a dummy fragment shader like you mentioned as workaround.

**Comment by LukasBanana** [comment]
Thanks for pointing out that issue. This should be fixed with commit f75ca5f.
