### ISSUE TITLE
CreateBuffer w. > 1MB bind=VertexBuffer on static build crashes 

### ISSUE THREAD

**Issue by dmiller423** [LukasBanana/LLGL#73]
Not much more to say,  built static lib using clang modified your own triangle test code change buffer size to 2MB and crash.
Building with clang 12 on win64

**Comment by LukasBanana** [comment]
What renderer did you use and can you share some example code?

**Comment by LukasBanana** [comment]
I just tested this with all backends and it works fine (200 MB):
```cpp
LLGL::BufferDescriptor vertexBufferDesc;
{
    vertexBufferDesc.size           = 200000000; // 200 MB
    vertexBufferDesc.bindFlags      = LLGL::BindFlags::VertexBuffer;
    vertexBufferDesc.vertexAttribs  = vertexFormat.attributes;
}
LLGL::Buffer* vertexBuffer = renderer->CreateBuffer(vertexBufferDesc);
renderer->WriteBuffer(*vertexBuffer, 0, vertices, sizeof(vertices));
```
At 2 GB I get an  `VK_ERROR_OUT_OF_DEVICE_MEMORY` error code from the Vulkan backend, even though my GPU has 8 GB or VRAM.
Nothing to be concerned about at the moment, though.
