### ISSUE TITLE
WebGPU backend

### ISSUE THREAD

**Issue by jayrulez** [LukasBanana/LLGL#87]
Hello, do you have plans for a WebGPU backend?

**Comment by LukasBanana** [comment]
I don't have plans to add any web based backends such as WebGPU or WebGL. I also don't have enough experience with WebAssembly to start looking into it, not even mentioning how much time goes into the backends LLGL already has.

**Comment by LukasBanana** [comment]
@jayrulez FYI: I started with a branch to test LLGL in HTML5 via WebAssembly/Emscripten (see [dev-wasm](https://github.com/LukasBanana/LLGL/tree/dev-wasm) branch). Any help here on how to deploy this without having to launch Chrome with a whole bunch of command line arguments [1] to enable Wasm support is highly appreciated. WebGPU might be a candidate for a future backend after all :)

[1] https://github.com/LukasBanana/LLGL/tree/dev-wasm/docu#webassembly-wasm

**Comment by LukasBanana** [comment]
**Update (4/22/2026)**:
I just pushed a work-in-process branch [dev-wgpu](https://github.com/LukasBanana/LLGL/tree/dev-wgpu) to add WebGPU support to LLGL. Please note that this is in its very early stages and can only be considered experimental until it is merged into the main branch.
