### ISSUE TITLE
Implementing a GPU-to-CPU Image Readback Functionality

### ISSUE THREAD

**Issue by lemoon** [LukasBanana/LLGL#88]
Hi,all. 
    Currently, there is a need to develop a mechanism to read the rendered images from the GPU back to the CPU, similar to the functionality provided by glReadPixels in OpenGL. This feature would enable efficient data transfer and processing between the GPU and CPU, allowing for further analysis, manipulation, or storage of the rendered images on the CPU side.

**Comment by LukasBanana** [comment]
Hi,

the primary function in LLGL to retrieve texture data from the GPU is [`RenderSystem::ReadTexture`](https://github.com/LukasBanana/LLGL/blob/master/include/LLGL/RenderSystem.h#L409). You can either render into a texture directly using a `RenderTarget` or read from the framebuffer (similar to `glReadPixels`) by copying the contents of the framebuffer into a texture using [`CopyTextureFromFramebuffer`](https://github.com/LukasBanana/LLGL/blob/master/include/LLGL/CommandBuffer.h#L304). Either way you will have to work with an instance of the `Texture` interface.

Hope that answers your questions.
Laura

**Comment by lemoon** [comment]
> Hi,
> 
> the primary function in LLGL to retrieve texture data from the GPU is [`RenderSystem::ReadTexture`](https://github.com/LukasBanana/LLGL/blob/master/include/LLGL/RenderSystem.h#L409). You can either render into a texture directly using a `RenderTarget` or read from the framebuffer (similar to `glReadPixels`) by copying the contents of the framebuffer into a texture using [`CopyTextureFromFramebuffer`](https://github.com/LukasBanana/LLGL/blob/master/include/LLGL/CommandBuffer.h#L304). Either way you will have to work with an instance of the `Texture` interface.
> 
> You can also take a look at how `ExampleBase` does it: First capture the frame via [`CaptureFramebuffer`](https://github.com/LukasBanana/LLGL/blob/master/examples/Cpp/ExampleBase/ExampleBase.cpp#L649), then save the texture to a PNG file in [`SaveTextureWithRenderer`](https://github.com/LukasBanana/LLGL/blob/master/examples/Cpp/ExampleBase/ExampleBase.cpp#L584).
> 
> Hope that answers your questions. Laura

Thank you, this is very helpful to me.

**Comment by LukasBanana** [comment]
This is not implemented for OpenGLES yet but desktop OpenGL is fine. It shouldn't take too long to implement it for GLES,
 though.

**Comment by LukasBanana** [comment]
Can this ticket be closed or is there still an issue with reading back framebuffer data?

**Comment by lemoon** [comment]
> @lemoon did you run into this exception or how did you find this unimplemented function? In other words, how urgent do you need this functionality for GLES?

Hi, LukasBanana. I expect to run on multiple platforms, including Android, MacOS, Windows, iOS, and Linux. So there is a high probability that this feature will be used on some low-end devices.

**Comment by lemoon** [comment]
> Can this ticket be closed or is there still an issue with reading back framebuffer data?

You can close this issue for now, and I will provide specific feedback based on the specific scenario in the future.
