### ISSUE TITLE
Missing include in VKPipelineState.h and VKPipelineBarrier.h ?

### ISSUE THREAD

**Issue by HITOA** [LukasBanana/LLGL#97]
I had a small issue while compiling the llgl vulkan renderer. Two file (VKPipelineState.h and VKPipelineBarrier.h) was throwing exception at me (std::uint32_t undefined for example). I just included cstdint at the top of the file and it seems to work fine now.

**Comment by LukasBanana** [comment]
Hi, can you please share what platform and compiler toolchain you are using?
And do I understand correctly, both files needed the extra `#include`-directive?

**Comment by HITOA** [comment]
I'm on linux (6.4.12-arch1-1) with a wayland window manager. 
on CLion, using the bundled cmake that come with CLion. 
compiler are gcc/g++.

That's correct, i had to add ```#include<cstdint>``` to both header file or a bunch of stuff was undefined.

**Comment by LukasBanana** [comment]
Thanks for bringing it up, I just confirmed the issue in my Arch Linux VM. Fixed with c6c59cf.
